

set(SVMEMLS_DEFINITIONS "")
set(SVMEMLS_NEEDED_LIBS SVMEMLS)

if(WIN32 OR (CYGWIN AND NOT IS64))
	#no SVMEMLS for x32
endif()

if(LINUX AND IS64)
	#no SVMEMLS for linux
endif()

if(IS64 AND (WIN32 OR CYGWIN))
unset(SVMEMLS_INCLUDE_DIR)
	set(SVMEMLS_PATH_PREFIX "SVMEMLS-2013.08.10/win/x64")
	set(SVMEMLS_FULL_PATH "${LicensedLibs_Bin_Directory}${SVMEMLS_PATH_PREFIX}")
	set(SVMEMLS_LIB_DIR "${SVMEMLS_FULL_PATH}" CACHE TYPE PATH)
	set(SVMEMLS_POSSIBLE_INCLUDE_DIR "${SVMEMLS_FULL_PATH}" CACHE TYPE PATH)
endif()

find_path(SVMEMLS_INCLUDE_DIR SVMEMLS.h HINTS ${SVMEMLS_POSSIBLE_INCLUDE_DIR})

GENLIBS(SVMEMLS_LIBRARY "${SVMEMLS_NEEDED_LIBS}" "SVMEMLS" "${SVMEMLS_LIB_DIR}")
set(SVMEMLS_LIBRARY ${SVMEMLS_SVMEMLS_LIBRARY})

include_directories(${SVMEMLS_INCLUDE_DIR})
link_directories(${SVMEMLS_LIB_DIR})
add_definitions(${SVMEMLS_DEFINITIONS})


